[2021-09-30 19:21:45,360] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: etl_dag.copy_from_hdfs 2021-09-28T01:30:00+00:00 [queued]>
[2021-09-30 19:21:45,411] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: etl_dag.copy_from_hdfs 2021-09-28T01:30:00+00:00 [queued]>
[2021-09-30 19:21:45,411] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-09-30 19:21:45,411] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-09-30 19:21:45,411] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-09-30 19:21:45,441] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): copy_from_hdfs> on 2021-09-28T01:30:00+00:00
[2021-09-30 19:21:45,458] {standard_task_runner.py:52} INFO - Started process 1699553 to run task
[2021-09-30 19:21:45,481] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'copy_from_hdfs', '2021-09-28T01:30:00+00:00', '--job-id', '418', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpoi0sidph', '--error-file', '/tmp/tmpijcw47hd']
[2021-09-30 19:21:45,482] {standard_task_runner.py:77} INFO - Job 418: Subtask copy_from_hdfs
[2021-09-30 19:21:45,594] {logging_mixin.py:104} INFO - Running <TaskInstance: etl_dag.copy_from_hdfs 2021-09-28T01:30:00+00:00 [running]> on host kseniya-B85M-D3V
[2021-09-30 19:21:45,762] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=copy_from_hdfs
AIRFLOW_CTX_EXECUTION_DATE=2021-09-28T01:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-28T01:30:00+00:00
[2021-09-30 19:22:11,988] {python.py:151} INFO - Done. Returned value was: None
[2021-09-30 19:22:12,059] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=copy_from_hdfs, execution_date=20210928T013000, start_date=20210930T162145, end_date=20210930T162212
[2021-09-30 19:22:13,123] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-09-30 19:22:13,136] {local_task_job.py:149} INFO - Task exited with return code 0
