[2021-09-30 19:21:17,129] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: etl_dag.copy_from_hdfs 2021-09-28T01:00:00+00:00 [queued]>
[2021-09-30 19:21:17,160] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: etl_dag.copy_from_hdfs 2021-09-28T01:00:00+00:00 [queued]>
[2021-09-30 19:21:17,161] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-09-30 19:21:17,161] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-09-30 19:21:17,161] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-09-30 19:21:17,180] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): copy_from_hdfs> on 2021-09-28T01:00:00+00:00
[2021-09-30 19:21:17,184] {standard_task_runner.py:52} INFO - Started process 1698317 to run task
[2021-09-30 19:21:17,189] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'copy_from_hdfs', '2021-09-28T01:00:00+00:00', '--job-id', '416', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpqj8og3rw', '--error-file', '/tmp/tmpt7enfi9r']
[2021-09-30 19:21:17,189] {standard_task_runner.py:77} INFO - Job 416: Subtask copy_from_hdfs
[2021-09-30 19:21:17,268] {logging_mixin.py:104} INFO - Running <TaskInstance: etl_dag.copy_from_hdfs 2021-09-28T01:00:00+00:00 [running]> on host kseniya-B85M-D3V
[2021-09-30 19:21:17,390] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=copy_from_hdfs
AIRFLOW_CTX_EXECUTION_DATE=2021-09-28T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-28T01:00:00+00:00
[2021-09-30 19:21:35,827] {python.py:151} INFO - Done. Returned value was: None
[2021-09-30 19:21:35,849] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=copy_from_hdfs, execution_date=20210928T010000, start_date=20210930T162117, end_date=20210930T162135
[2021-09-30 19:21:35,929] {local_task_job.py:149} INFO - Task exited with return code 1
